

Parameters:
  AvailabilityZone1: 
    Default: us-east-1a
    Description: "Avaibalbility Zone"
    Type: String
  
  AvailabilityZone2: 
    Default: us-east-1b
    Description: "Second Availability Zone"
    Type: String
    
  PublicSubnetCIDR: 
    Default: 10.0.1.0/24
    Description: "Public Subnet CIDR"
    Type: String
  
  PrivateSubnetCIDR1: 
    Default: 10.0.2.0/24
    Description: "Private Subnet CIDR"
    Type: String
  
  PrivateSubnetCIDR2: 
    Default: 10.0.3.0/24
    Description: "Private Subnet CIDR"
    Type: String

  VPCCIDR: 
    Default: 10.0.0.0/16
    Description: "VPC CIDR"
    Type: String
  
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    ConstraintDescription: must be a valid EC2 instance type

  EnvironmentName:
    Description: Environment Name
    Type: String
    AllowedValues: [development, production]
    ConstraintDescription: must be development or production

Mappings:
  
  EnvironmentToInstanceType:
    development:
      instanceType: t2.micro
    production:
      instanceType: t2.small

  AWSRegion:
    us-east-1:
      HVM64: "ami-09d3b3274b6c5d4aa"
    us-east-2:
      HVM64: ami-05d72852800cbf29e
    us-west-1:
      HVM64: ami-0577b787189839998
    us-west-2:
      HVM64: ami-0518bb0e75d3619ca



Resources:
# VPC 
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties: 
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'

#public subnetwork for jumpbox
  JumpBoxPublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties: 
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetCIDR
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Ref AvailabilityZone1

  InternetGateway:
     Type: AWS::EC2::InternetGateway
  
  InternetAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

#route table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      
 #PrivateRouteTable:
  # Type: AWS::EC2::RouteTable
   #Properties:
    # VpcId: !Ref VPC
  
  PublicRoute: 
    Type: "AWS::EC2::Route"
    DependsOn: InternetAttachGateway
    Properties: 
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref PublicRouteTable



  JumpBoxPublicSubnetRouteTableAssociation: 
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref JumpBoxPublicSubnet

# subnetwork for front end app instance
  FrontEndAppSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties: 
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCIDR2
      AvailabilityZone: !Ref AvailabilityZone2

#private subnetwork for app server instance
  AppServerPrivateSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties: 
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCIDR1
      AvailabilityZone: !Ref AvailabilityZone1

  # AppServerPrivateSubnetRouteTableAssociation: 
  #   Type: "AWS::EC2::SubnetRouteTableAssociation"
  #   Properties: 
  #    # RouteTableId: !Ref PrivateRouteTable
  #     SubnetId: !Ref AppServerPrivateSubnet


#JumpBox Instance
  JumpBoxEC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !FindInMap [EnvironmentToInstanceType, !Ref 'EnvironmentName', instanceType]
      ImageId: !FindInMap [AWSRegion, !Ref 'AWS::Region', HVM64]
      KeyName: InstanceKey
      AvailabilityZone: !Ref AvailabilityZone1
      # SecurityGroupIds:
      #   - !Ref JumpBoxSecurityGroup
      NetworkInterfaces:
        - SubnetId: !Ref JumpBoxPublicSubnet
          GroupSet: 
            - !Ref JumpBoxSecurityGroup
          DeviceIndex: 0
#JumpBox security group
  JumpBoxSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VPC
  JumpBoxSecurityGroupInbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref JumpBoxSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0
  JumpBoxSecurityGroupOutbound1:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref JumpBoxSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      DestinationSecurityGroupId: !Ref PPrivateSecurityGroup
  
  JumpBoxSecurityGroupOutbound2:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref JumpBoxSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      DestinationSecurityGroupId: !Ref FrontEndAppSecurityGroup

#App server instance
  PPrivateEC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [AWSRegion, !Ref 'AWS::Region', HVM64]
      KeyName: InstanceKey
      AvailabilityZone: !Ref AvailabilityZone1
      NetworkInterfaces:
        - SubnetId: !Ref AppServerPrivateSubnet
          GroupSet: 
            - !Ref PPrivateSecurityGroup
          DeviceIndex: 0
#app server security group
  PPrivateSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VPC
  PPrivateSecurityGroupInbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref PPrivateSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId: !Ref JumpBoxSecurityGroup

  # PPrivateSecurityGroupInbound2:
  #   Type: AWS::EC2::SecurityGroupIngress
  #   Properties:
  #     GroupId: !Ref PPrivateSecurityGroup
  #     IpProtocol: tcp
  #     FromPort: 22
  #     ToPort: 22
  #     SourceSecurityGroupId: !Ref FrontEndAppSecurityGroup

#Front end App instance
  FrontEndAppEC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [AWSRegion, !Ref 'AWS::Region', HVM64]
      AvailabilityZone: !Ref AvailabilityZone2
      KeyName: InstanceKey
      NetworkInterfaces:
        - SubnetId: !Ref FrontEndAppSubnet
          GroupSet: 
            - !Ref FrontEndAppSecurityGroup
          DeviceIndex: 0

#front end app security group
  FrontEndAppSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VPC
  FrontEndAppSecurityGroupInbound1:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref FrontEndAppSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId: !Ref JumpBoxSecurityGroup

  # FrontEndAppSecurityGroupOutbound1:
  #   Type: AWS::EC2::SecurityGroupEgress
  #   Properties:
  #     GroupId: !Ref FrontEndAppSecurityGroup
  #     IpProtocol: tcp
  #     FromPort: 22
  #     ToPort: 22
  #     DestinationSecurityGroupId: !Ref PPrivateSecurityGroup

  # FrontEndAppSecurityGroupOutbound2:
  #   Type: AWS::EC2::SecurityGroupEgress
  #   Properties:
  #     GroupId: !Ref FrontEndAppSecurityGroup
  #     IpProtocol: tcp
  #     FromPort: 22
  #     ToPort: 22
  #     DestinationSecurityGroupId: !Ref FrontEndAppSecurityGroup

#DB Instance
  
