Parameters:

  AvailabilityZone1: 
    Default: us-east-1a
    Description: "Avaibalbility Zone"
    Type: String

  EnvironmentName:
    Description: Environment Name
    Type: String
    AllowedValues: [development, production]
    ConstraintDescription: must be development or production

Mappings:
  
  EnvironmentToInstanceType:
    development:
      instanceType: t2.micro
    production:
      instanceType: t2.small

  AWSRegion:
    us-east-1:
      HVM64: ami-09d3b3274b6c5d4aa
    us-east-2:
      HVM64: ami-05d72852800cbf29e
    us-west-1:
      HVM64: ami-0577b787189839998
    us-west-2:
      HVM64: ami-0518bb0e75d3619ca

Resources:  
#JumpBox Instance
  JumpBoxEC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !FindInMap [EnvironmentToInstanceType, !Ref 'EnvironmentName', instanceType]
      ImageId: !FindInMap [AWSRegion, !Ref 'AWS::Region', HVM64]
      KeyName: InstanceKey
      AvailabilityZone: !Ref AvailabilityZone1
      # SecurityGroupIds:
      #   - !Ref JumpBoxSecurityGroup
      NetworkInterfaces:
        - SubnetId: !ImportValue JumpBoxPublicSubnetImport
          GroupSet: 
            - !ImportValue JumpBoxSecurityGroupImport
          DeviceIndex: 0

